### ISSUE TITLE
Normal color vision option in dichromat (identity function)

### ISSUE THREAD

**Issue by brianwdavis** [jonclayden/shades#3]
I was using `purrr` to simulate a palette with all the color deficiencies, which works fine. But it would be great if I could also include an option for "normal", which would return the palette unchanged for comparison.

```
library(magrittr)
library(purrr)

c("prot", "deut", "trit") %>% 
  map(~dichromat(blues9, type = .))
```

Having an option for "normal" inside that first vector would mean being able to generate a figure like this in just a couple lines:

![image](https://user-images.githubusercontent.com/13338560/35016658-9f43e142-fae7-11e7-84cf-8e92ac6b075f.png)

I imagine this is an easier feature than vectorizing dichromat to accept a vector of arguments to `type =`.

**Comment by jonclayden** [comment]
Good thought, thanks. In fact, vectorising over `type` should be manageable and would be consistent with other package functions, so I'll look into it.

**Comment by jonclayden** [comment]
OK, with the current development version you should be able to do things like

```r
blues9 %>% dichromat(c("n","p","d","t")) %>% swatch
```

If you could check that it works for you, I'll close the issue. Thanks again for the suggestion!

**Comment by brianwdavis** [comment]
Looks great to me, thanks!
