### ISSUE TITLE
Package doesn't load since R 3.6.0 upgrade

### ISSUE THREAD

**Issue by cfredemb** [jonclayden/shades#8]
Package was working fine on my old R 3.5.2 workspace, but hasn't loaded since upgrading to 3.6

`library(shades)
Error: package or namespace load failed for ‘shades’:
 .onLoad failed in loadNamespace() for 'shades', details:
  call: .bradfordXYZtoLMS %*% xyz
  error: non-conformable arguments`

Session info:

`sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_Australia.1252 
[2] LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0   `

**Comment by jonclayden** [comment]
Hi. This reminds me of an issue that was patched in shades v1.3.1. Are you using a version of the package older than that?

**Comment by cfredemb** [comment]
No, I was/am using 1.4.0 
Reinstall of the package and R (again) removed the error, so that's that.

Thanks for the compact and useful package

**Comment by jonclayden** [comment]
Glad it has sorted itself out. There was a change to the behaviour of a core function in R v3.6.0, which was the cause of this issue, so I'm not surprised your upgrade made you see it for the first time.
